# 发送发配置信息
source_dir: F:\cxxzoom\ftp\test\
zip_compress_dir: F:\cxxzoom\ftp\public\zip\
zip_split_dir: F:\cxxzoom\ftp\public\chunk\

# 下面是接收方的配置文件
chunk_save_dir: F:\cxxzoom\ftp\public2\chunk\
chunk_unzip_dir: F:\cxxzoom\ftp\public2\